### PR TITLE
loosen illuminate dependencies

### PR DESCRIPTION
**Pull request by suwardany**
Hello Jason,

We're using this package over at Cartalyst, it works with Laravel 5's components without any additional changes.

Thanks!

Signed-off-by: Suhayb Wardany <me@suw.me>

### CODE REVIEW

**Comment by jasonlewis** [comment]
Excellent, cheers mate. Much appreciated.

**Comment by jasonlewis** [comment]
I'll push a new tag when I get the chance.

**Comment by suwardany** [comment]
Thanks @jasonlewis

**Comment by suwardany** [comment]
Hey @jasonlewis sorry for nagging, any chances you could push a tag for this? The only pending lib for us :)

Thanks!

**Pull request merged**
